export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";
export const LOG_OUT = "LOG_OUT";
export const KEEP_LOGIN = "KEEP_LOGIN";

export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";

export const GET_PRODUCT_BY_ID_REQUEST = "GET_PRODUCT_BY_ID_REQUEST";
export const GET_PRODUCT_BY_ID_FAILURE = "GET_PRODUCT_BY_ID_FAILURE";
export const GET_PRODUCT_BY_ID_SUCCESS = "GET_PRODUCT_BY_ID_SUCCESS";

export const ADD_PRODUCTS_REQUEST = "ADD_PRODUCT_REQUEST";
export const ADD_PRODUCTS_FAILURE = "ADD_PRODUCTS_FAILURE";
export const ADD_PRODUCTS_SUCCESS = "ADD_PRODUCTS_SUCCESS";

export const UPDATE_PRODUCTS_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCTS_FAILURE = "UPDATE_PRODUCTS_FAILURE";
export const UPDATE_PRODUCTS_SUCCESS = "UPDATE_PRODUCTS_SUCCESS";

export const DELETE_PRODUCTS_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCTS_FAILURE = "DELETE_PRODUCTS_FAILURE";
export const DELETE_PRODUCTS_SUCCESS = "DELETE_PRODUCTS_SUCCESS";

export const GET_TOP_SALE_REQUEST = "GET_TOP_SALE_REQUEST";
export const GET_TOP_SALE_FAILURE = "GET_TOP_SALE_FAILURE";
export const GET_TOP_SALE_SUCCESS = "GET_TOP_SALE_SUCCESS";

export const GET_POP_TAG_REQUEST = "GET_POP_TAG_REQUEST";
export const GET_POP_TAG_FAILURE = "GET_POP_TAG_FAILURE";
export const GET_POP_TAG_SUCCESS = "GET_POP_TAG_SUCCESS";

export const GET_ORDERS_REQUEST = "GET_ORDERS_REQUEST";
export const GET_ORDERS_FAILURE = "GET_ORDERS_FAILURE";
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";

export const GET_ORDER_DETAIL_REQUEST = "GET_ORDER_DETAIL_REQUEST";
export const GET_ORDER_DETAIL_FAILURE = "GET_ORDER_DETAIL_FAILURE";
export const GET_ORDER_DETAIL_SUCCESS = "GET_ORDER_DETAIL_SUCCESS";

export const UPDATE_ORDER_REQUEST = "UPDATE_ORDER_REQUEST";
export const UPDATE_ORDER_FAILURE = "UPDATE_ORDER_FAILURE";
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS";
