export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const LOG_OUT = "LOG_OUT";
export const KEEP_LOGIN = "KEEP_LOGIN";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const GET_PRODUCT_HOT_REQUEST = "GET_PRODUCT_HOT_REQUEST";
export const GET_PRODUCT_HOT_SUCCESS = "GET_PRODUCT_HOT_SUCCESS";
export const GET_PRODUCT_HOT_FAILURE = "GET_PRODUCT_HOT_FAILURE";

export const GET_POST_REQUEST = "GET_POST_REQUEST";
export const GET_POST_SUCCESS = "GET_POST_SUCCESS";
export const GET_POST_FAILURE = "GET_POST_FAILURE";
